### ISSUE TITLE
将来的な消費税変更に伴う対応について

### ISSUE THREAD

**Issue by crosscontinue** [vektor-inc/bill-vektor#101]
現在導入を検討しておりますが、上記について2点質問がございます。

1) 将来的に税率の設定変更画面は実装される予定でしょうか？
2) 実装されない場合、テーマを解析して税率を調整しようと思うのですが、その場合、古い税率での見積/請求の金額まで、調整後の税率になってしまうのでしょうか？

**Comment by kurudrive** [comment]
BillVektorは自社で利用しておりますので、
税率の変更機能を実装しないと弊社会計業務に支障が出るため実装予定です。
過去の請求書などは古い税率のままでちゃんと表示されるようにする想定です。

よろしくお願いいたします。

**Comment by kpyon** [comment]
10月からの消費税増税への対応は順調でしょうか？

**Comment by kurudrive** [comment]
順調ではありませんが対応は予定しております。
