### ISSUE TITLE
【機能追加要望】納品書発行

### ISSUE THREAD

**Issue by sakoda-shingo** [vektor-inc/bill-vektor#102]
はじめまして。最近、エクセルで管理していたものを移行中です。
今後、納品書が発行できる機能が追加されると嬉しいです。
ご検討の程、宜しくお願いいたします。

**Comment by tomg25** [comment]
はじめまして。私も同意です。
仕様はほぼ請求書と同じで、金額のみ表示か非表示が選べれば、印刷（出力）時のタイトルを「納品書」とするだけでも良いのかなと思いますので、ぜひ導入のほどよろしくお願いいたします。

**Comment by kurudrive** [comment]
ご意見ありがとうございます。
通常業務など多忙のため具体的な実装時期は名言できませんが、実装を検討させていただきます。

**Comment by kurudrive** [comment]
おまたせいたしました。
有料ではありますが領収書・納品書発行プラグインを作りました。
https://billvektor.com/add-on/
基本「領収書」ですが、各編集ページで「納品書」など任意の名称に変更できますのでご検討くださいませ。
