### ISSUE TITLE
見積書についての追加機能についての要望です。

### ISSUE THREAD

**Issue by apricot-tea** [vektor-inc/bill-vektor#113]
はじめまして。素晴らしいものをお作りくださりありがとうございます。
早速ですが、追加いただきたい機能があり書き込みさせていただきました。

1つ目。
見積書の単価につきましての要望です。
現在の仕様では、単価の欄に小数点を含む数値を入力すると、計算は間違いなく表示されるのですが、PDFに出力する際に小数点以下の数字が表示されない仕様かと思います。
印刷物の見積書などを作成させていただこうと思い、小数点以下の数字も表示していただけませんでしょうか？

2つ目。
見積書と同時に、注文書を発行できる機能を追加していただけませんでしょうか？

ご検討のほどよろしくお願い申し上げます。

**Comment by kurudrive** [comment]
んー・・・いやー・・・
円で小数点以下の金額を使うのはちょっと相当レアケースかなーと・・・。
消費税も全部切り捨てが基本なので、円の単位で小数点がついている書類を
僕が目にした事が無いレベルですが...

あー、もしかして小さな部品で1つ1.4円を300個くらい注文されるとかそういう類ですかね...

注文書や納品書・領収書は需要は理解しているのですが、現状無料でお金になっておらず、
本業も火の車なので開発工数が捻出できていないというのが実情です...。

**Comment by kurudrive** [comment]
@apricot-tea

billvektorを最新版にして、下記子テーマを適用すると小数点表示されます。
https://github.com/vektor-inc/bill-vektor-child

納品書などは工数かかるのでご容赦を...。

|彡 ｻｯ!

**Comment by apricot-tea** [comment]
お忙しい中、ご対応くださりありがとうございます。
早速、子テーマにて利用させていただきます。
