### ISSUE TITLE
非課税欄追加

### ISSUE THREAD

**Issue by naoya37** [vektor-inc/bill-vektor#116]
立替経費の請求時に必要な非課税欄を追加いただきたいです。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
ご利用ありがとうございます。
ちょっと構造上結構時間のかかりそうな事項になるのですが、ごめんなさい、懐事情に余裕がなさ過ぎるので、当面対応は難しいです。
消費税についてのラジオボタンで「品目毎に予め消費税込の金額で入力する」を選択いただいたり、立替品目は別請求書で発行して「品目毎に予め消費税込の金額で入力する」を選択いただくなど、運用でカバーよろしくお願いいたします。

**Comment by kurudrive** [comment]
対応済み close
