### ISSUE TITLE
[0.9.3] 送付済PDFファイルのアップロードができない

### ISSUE THREAD

**Issue by nullpopopo** [vektor-inc/bill-vektor#119]
バージョン 0.9.2 ではできていた送付済PDFファイルのアップロードが、0.9.3では旨く機能していないようです。Select Fileのボタンをクリックしても、ファイル選択の画面が起動しません。 0.9.2 のときにアップロードしたPDFファイルをView Fileで閲覧することはできました。

**Comment by kurudrive** [comment]
報告有難うございます。
jsのキャッシュが原因だと思いますので、ブラウザのキャッシュを消して再読込してみてください。
一応キャッシュ対策版を後ほどアップします。

**Comment by nullpopopo** [comment]
ご確認ありがとうございます。ブラウザのキャッシュを削除して再読込したところ、PDFファイルのアップロードができました。
