### ISSUE TITLE
BillVektor Receipt 領収書が作れない

### ISSUE THREAD

**Issue by sevenseconds777** [vektor-inc/bill-vektor#122]
BillVektor Receiptを購入しましたが
作成済みの請求書を開き、「この内容で領収書を発行」ボタンを押しても
領収書は作成されず、何も書かれていない請求書が複製されるだけです。

**Comment by kurudrive** [comment]
ご購入ありがとうございます。
BillVektorのバージョンはいつくをご利用でしょうか？
BillVektor 1.0.0 以降でないと正常に動作しませんので、
まずはBillVektorのバージョンをご確認ください。

**Comment by kurudrive** [comment]
大変失礼しました。
修正アップデートいたしましたので、プラグインをアップデートしてご確認くださませ。

**Comment by sevenseconds777** [comment]
ありがとうございました。

**Comment by kurudrive** [comment]
いえいえ、ご迷惑おかけしました。
今後ともBillVektorをよろしくお願いいたします。
