### ISSUE TITLE
請求者情報入力を２行にしたい

### ISSUE THREAD

**Issue by kojkcip** [vektor-inc/bill-vektor#128]
会社名が長く、印刷で縦に印刷しようとすると会社名が途中で改行されてしまいます
設定画面の請求者情報入力画面で、２行にして会社名を入力するには、どうすればよろしいでしょうか？

**Comment by kurudrive** [comment]
アップデートしてから設定画面の請求者情報入力画面から2行にしてみてください（・ｗ・

**Comment by kojkcip** [comment]
アップデートとは、テーマのアップデートでしょうか？
簡単な内容なのかもしれませんが、初心者なのでよくわからなくてすいません

詳細を教えていただけると助かります

**Comment by kurudrive** [comment]
テーマの更新通知が出ていましたらテーマをアップデートしてください。
