### ISSUE TITLE
エクスポート時のエラーについて

### ISSUE THREAD

**Issue by gohho** [vektor-inc/bill-vektor#135]
Fatal error: Uncaught Error: [] operator not supported for strings in/以下ドメイン名... 
とエラーが出てしまいます。
どのような対処が必要でしょうか。
ご指南頂ければ幸いです。
よろしくお願い申し上げます。

**Comment by kurudrive** [comment]
サーバーのPHPのバージョンはわかりますか？

**Comment by kurudrive** [comment]
返信がありませんので一旦closeします。
