### ISSUE TITLE
BillVektor Receipt が上手く動きません。

### ISSUE THREAD

**Issue by hidesakura** [vektor-inc/bill-vektor#138]
WordPress 5.2.2
最新のBillVektor Receipt 

プラグイン有効化後、「設定 > パーマリンク設定」を一度保存。
請求書から領収書発行しても、領収書画面に移行されず
請求書に下書きとして保存される。

助けてください・・納品できずに困っています。

**Comment by kurudrive** [comment]
確認しますのでしばしお待ちください。

**Comment by kurudrive** [comment]
今確認した限りは正常に動作しました。
領収書発行したら、領収書として下書き保存され、
それを公開して表示すると領収書になると思いますがいかがでしょうか？
領収書の下書きではなく請求書の下書きになるという事ですか？

**Comment by hidesakura** [comment]
請求書から
「この内容で領収書を発行」を押すと
領収書に切り替わらず、請求書がコピーされたような状態になります。

見積書から
「この内容で請求書を発行」は上手くいきます。

領収書そのものは普通に入力すれば発行できます。

----------------------------------------------------
農業はじめました_____
農薬不使用・化学肥料不使用 [ 安心こだわり栽培 ]
ファーム さくらいろ
https://farm-sakurairo.com
----------------------------------------------------
Design SAKURAIRO
http://d-sakurairo.com/
〒377-0433
群馬県吾妻郡中之条町折田417-1
TEL.0279-26-2668
----------------------------------------------------
クリエイター佐倉英寿
chip.dale.hide@gmail.com
hide@d-sakurairo.com
TEL.080-1127-3750
----------------------------------------------------


2019年8月28日(水) 13:42 Hidekazu Ishikawa <notifications@github.com>:

**Comment by kurudrive** [comment]
見た目はほとんど同じですが、左のメニューで見ると領収書に切り替わっていませんか？
左のメニューも請求書のままですか？

**Comment by hidesakura** [comment]
切り替わりません。

「この内容で領収書を発行」を押すと
添付画像のように
項目も消えたものが表示されます。

[image: スクリーンショット 2019-08-28 13.52.27.png]


----------------------------------------------------
農業はじめました_____
農薬不使用・化学肥料不使用 [ 安心こだわり栽培 ]
ファーム さくらいろ
https://farm-sakurairo.com
----------------------------------------------------
Design SAKURAIRO
http://d-sakurairo.com/
〒377-0433
群馬県吾妻郡中之条町折田417-1
TEL.0279-26-2668
----------------------------------------------------
クリエイター佐倉英寿
chip.dale.hide@gmail.com
hide@d-sakurairo.com
TEL.080-1127-3750
----------------------------------------------------


2019年8月28日(水) 13:50 Hidekazu Ishikawa <notifications@github.com>:

**Comment by kurudrive** [comment]
す、すみません、GitHubへの返信になるので画像を添付しても確認ができません。

firestrage などにアップしてURLをご連絡いただけますでしょうか？

お手数おかけしますがよろしくお願いいたします。

**Comment by kurudrive** [comment]
※ メールの署名もGitHubのコメントに投稿されてしまいますので、メールから返信の際はご注意ください。
※ 過去の署名は私の方で消しました。

**Comment by kurudrive** [comment]
あと、見積書から請求書の発行は問題なく動作しますか？

**Comment by hidesakura** [comment]
見積書から
「この内容で請求書を発行」は上手くいきます。

**Comment by kurudrive** [comment]
症状が再現出来ないと解消する事が出来ませんので、
とりあえず画像は下記などにアップして、そのURLを返信ください。

https://firestorage.jp/

以下のバージョン（"最新版"ではなく数字）をお知らせください。
BillVektor
BliiVektor Reciept

以上よろしくお願いいたします。

**Comment by kurudrive** [comment]
あと、ご利用のPHPのバージョンもよろしくお願いいたします。

**Comment by hidesakura** [comment]
「この内容で領収書を発行」を押すと内容が消えるだけです。
https://14.gigafile.nu/0904-d8a47e1339dca8b977594f6835fc6f23b

PHP7.1
BillVektor　バージョン: 0.9.2
BliiVektor Reciept　バージョン 1.2.1

**Comment by kurudrive** [comment]
BillVektor Recieptの対応BillVektor は BillVektor 1.0.0 以降になります。
現在のBillVektorの最新版は 1.2.3 です。
テーマをアップデートしてご確認ください。

**Comment by hidesakura** [comment]
できました。
公式ページから先ほど落としたばかりなので
最新だと思い込んでいました。

ありがとうございました。

**Comment by kurudrive** [comment]
無事解決で何よりです。
本件Cloaseいたします。
