### ISSUE TITLE
RSSを取得できない　https://billvektor.com/feed/ 

### ISSUE THREAD

**Issue by kpyon** [vektor-inc/bill-vektor#140]
https://billvektor.com/feed/ の情報が取得できません。

トップお知らせ欄に以下のエラーが出ております。
Warning: Invalid argument supplied for foreach() in /home/xndt/xndt.xsrv.jp/public_html/bill/wp-content/themes/bill-vektor-child-master/index.php on line 112

RSSウジェットを設定しましたが、以下エラーが出ています。
RSS エラー: This XML document is invalid, likely due to invalid characters. XML error: Invalid character at line 39, column 35

**Comment by kurudrive** [comment]
配信側の問題でしたので記事修正しました。
報告ありがとうございました。
