### ISSUE TITLE
発行日の変更はできますか？

### ISSUE THREAD

**Issue by beatoyaji** [vektor-inc/bill-vektor#142]
すごくためになるシステムのご提供、大変感謝しております。
今後ともよろしくお願いします。

初歩的な質問で申し訳ありませんが、ひとつお尋ねします。

見積書、並びに請求書の発行日の変更は可能でしょうか。
公開日を編集してみましたが駄目だったようなので・・・

よろしくお願いします。

**Comment by kurudrive** [comment]
いや、公開日を編集すれば反映されるはずです。
プレビューなどでなく保存しなおしてキャッシュを消してリロードしても反映されませんか？

**Comment by beatoyaji** [comment]
早速のお返事ありがとうございます。
キャッシュクリア＆リロードで解決しました。
ありがとうございました。
