### ISSUE TITLE
領収書・請求書・見積書の発行元を選択できるようにしたい。

### ISSUE THREAD

**Issue by matchyishii** [vektor-inc/bill-vektor#144]
当社の場合は会社名と、ぶら下がっている複数の協会名で上記の書類を発行することがあります。発行元を複数登録して、それを書類発行時に選択できるようにしたい。

**Comment by kurudrive** [comment]
ご要望ありがとうございます。

しかしながら

* 発行元を複数切り替えるというケースが一般的ではない
* 発行元を複数切り替えるとなるとかなり工数のかかる改修となるが、改修費用の元が取れる目処がまったくない
* 他の優先作業事項が山積みであるため改修の余力がない

という理由により本件については改修作業は見送らせていただきます。

せっかくご要望いただきましたのにこのような回答となってしまい恐れ入りますが何卒ご理解いただけますと幸いです。
