### ISSUE TITLE
見積書数字入力欄に数字以外が入っていた場合の警告メッセージ回避

### ISSUE THREAD

**Issue by Raphael-D** [vektor-inc/bill-vektor#149]
はじめに。素晴らしい製品を開発していただきありがとうございます。とても使いやすくて重宝しております。
早速ですが本題に。

お客様にてお見積書作成時に、手違いで数字入力欄に¥マークが入っておりました。
それが原因で、請求書画面に以下の警告メッセージが多数表示されておりました。

>Warning: number_format() expects parameter 1 to be float, string given in

そこでご提案なのですが、数字入力欄に数字以外の文字が入っていた場合、自動で削除するか、保存前に警告メッセージを出すなどの処理を実装してはいかがでしょうか？

可能でしたらご対応のほどお願いいたします。

**Comment by HS-masa** [comment]
WordPressフォルダ内の「.htaccess」に「php_flag display_errors off」を追加すればメッセージはでません

**Comment by kurudrive** [comment]
1.7.3で
数字以外入力できないように変更しました
