### ISSUE TITLE
サイドバーにある「見積もり」のリンクを押下しても見積もりのリストが表示されません。

### ISSUE THREAD

**Issue by ktr-ohr** [vektor-inc/bill-vektor#153]
良きテーマ、プラグインをありがとうございます。

タイトルのとおり、
サイドバーにある「見積もり」を押下して、下記のようなURLに遷移しても見積もりのリストが表示されません。
https://xxxxx.com/estimate/

見積もりのリストを表示できるようにしていただきたいです。
ご確認よろしくお願い致します。

利用テーマver. 1.6.1

**Comment by kurudrive** [comment]
ご意見・ご報告ありがとうございます。
現在別件で立て込んでおりますので今後の対応課題とさせていただきます。
よろしくお願いいたします。

**Comment by HS-masa** [comment]
パーマリンクの設定が基本になっているか確認してください
他の設定だとサイドバーのリンクは動かないです

**Comment by kurudrive** [comment]
1.7.0 で対応しました。
