### ISSUE TITLE
トップページに表示されるリストに請求書・見積もりどちらも表示してほしい。

### ISSUE THREAD

**Issue by ktr-ohr** [vektor-inc/bill-vektor#154]
お世話になっております。
トップページに表示されるリストには請求書のみが表示され、見積もりは表示されません。
こちらは仕様でしょうか？
※こちらの設定ミスでしたらすみません。

もし、仕様でしたら、請求書・見積もりどちらも表示できるようにしていただけるとありがたいです。
よろしくお願い致します。

利用テーマver. 1.6.1

**Comment by HS-masa** [comment]
カテゴリー指定の見積りデータがないかカテゴリーそのものがないからかもです

**Comment by kurudrive** [comment]
仕様でしたが変更しました。

1.7.0 で対応しました。
