### ISSUE TITLE
品目を一覧から選択できるようにしてほしい

### ISSUE THREAD

**Issue by gounjp** [vektor-inc/bill-vektor#155]
BillVektorの利用を検討しております。
当方の取扱商材は非常に商品数が多いため、一覧から商品名を選択すると金額や単位が自動で入力されるようにできるようになればとても助かります。
ご検討いただけましたら幸いです。

**Comment by kurudrive** [comment]
ご意見ありがとうございます。
せっかくご要望いただきましたが、原状別件の開発事項が詰まっているのと、
ご要望いただきました内容に実装工数がかかりそうなので、弊社での実装は難しいです。
よいお返事ができず恐れ入ります。
何卒ご理解いただけますと幸いです。
