### ISSUE TITLE
請求書等でイレギュラーの場合の取引先名の敬称

### ISSUE THREAD

**Issue by HS-masa** [vektor-inc/bill-vektor#156]
いつも便利に使わせていただいています
ありがとうございます！

バージョンアップで取引先のイレギュラー登録ができるようになりまた便利になったのですが
印刷時にイレギュラーの場合は敬称が「御中」に固定されます
イレギュラーの場合は、名称の後に「様」など入力をするようにしたいのでできるなら
イレギュラー登録された書類の場合は、敬称が表示されないようにしていただけないでしょうか

以上、よろしくお願いいたします

**Comment by kurudrive** [comment]
@HS-masa ご提案ありがとうございます。
なるほど、確かに僕のケースでは全て御中で済んでいたのですが人名だったりは普通にありますね。
ちょっと今は別件が詰まっていてすぐ着手はできませんが対応したいと思います。

**Comment by kurudrive** [comment]
1.7.0 で対応しました。
