### ISSUE TITLE
PHPUnit が travis のままでコケる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/bill-vektor#160]
たぶん設定の問題だけだと思われる。

lightning などと同様に wp-env で phpunitが動くように再設定よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
PHP Unit の設定をしておきました。

**Comment by kurudrive** [comment]
@drill-lancer あーっリがとうございますー！助かります！
