### ISSUE TITLE
領収書のPDF保存時、見積書と請求書のようにファイル名が自動生成されない。

### ISSUE THREAD

**Issue by Daiki-Oshima** [vektor-inc/bill-vektor#162]
いつもLinghtningPro、BillVektorにお世話になっています。
素晴らしい製品を開発していただきありがとうございます。とても使いやすくて重宝しているところです。

早速ですが、有料の領収書生成プラグインを導入したのですが、各書類のPDF出力時は、見積書_サンプル様_内容_日付.pdfとなるのですが、領収書では、内容_サイト名.pdfとなってしまいます。

領収書は見積書や請求書と同様のファイル名の形式で出力されないのでしょうか。

よろしくお願いいたします。

**Comment by kurudrive** [comment]
@Daiki-Oshima 大変おまたせいたしました。
BillVektor 1.7.1 にて修正しましたのでアップデートの上ご確認ください。

**Comment by kurudrive** [comment]
対応済みにつきcloseします。

**Comment by Daiki-Oshima** [comment]
ご対応いただきありがとうございました！

今後ともよろしくお願いいたします。
==============================
Webクリエイター・Webディレクター
大嶋 大輝（Daiki Oshima）
***@***.***
TEL：080-6248-6391
==============================


2021年9月13日(月) 9:23 Hidekazu Ishikawa ***@***.***>:
