### ISSUE TITLE
ページが見つかりませんでしたと出る

### ISSUE THREAD

**Issue by Yukiya105** [vektor-inc/bill-vektor#164]
有料版の領収書発行プラグインを購入して使用していたのですが、保存を押して公開済みになっていることを確認してからリンクをクリックすると『ページが見つかりません』と表示されます。請求書発行では問題なく使用できますが、給料明細が使用できません。
これは、どうすれば良いのでしょうか？

**Comment by mthaichi** [comment]
WordPressの「設定」>「パーマリンク」で、値を変更せずにそのまま「設定を保存」し、再度お試しください。（外してたらすみません）

**Comment by kurudrive** [comment]
@Yukiya105 様

おそらく @mthaichi さんの書き込みの内容で問題なく使用できると思いますが如何でしょうか？
