### ISSUE TITLE
請求書の複製時に｢サイトで技術的な問題が発生しています｣が・・・

### ISSUE THREAD

**Issue by kawax2000** [vektor-inc/bill-vektor#168]
いつも利用させて頂き、ありがとうございます。
ここ何カ月か、請求書を複製する時に｢サイトで技術的な問題が発生しています｣が表示されます。
その後に元のページに戻ってリロードをかけると、ちゃんと複製されています。

情報として・・・
WordPress バーション5.8.2
現在のテーマ: BillVektor (バージョン 1.7.1)
現在のプラグイン: Classic Editor (バージョン 1.6.2 )
PHP バージョン8.0.13

エラー詳細
===============
エラータイプ E_ERROR が /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-content/themes/bill-vektor/inc/duplicate-doc/dupricate-doc-functions.php ファイルの 153 行目で発生しました。 エラーメッセージ: Uncaught Error: Call to undefined function each() in /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-content/themes/bill-vektor/inc/duplicate-doc/dupricate-doc-functions.php:153
Stack trace:
#0 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-content/themes/bill-vektor/inc/duplicate-doc/dupricate-doc-functions.php(195): bill_copy_post()
#1 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-includes/class-wp-hook.php(303): bill_copy_redirect()
#2 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-admin/admin.php(175): do_action()
#5 /var/www/vhosts/〇〇〇.jp/httpdocs/biz/wp-admin/post-new.php(10): require_once('...')
#6 {main}
  thrown

原因わかりますでしょうか？
宜しくお願い致します。

**Comment by kurudrive** [comment]
あぁ...PHP８ですか、なるほど...。報告ありがとうございます。

@mthaichi さん確認・対応お願いできますか？

**Comment by kurudrive** [comment]
@kawax2000

ご報告ありがとうございます。
対応済みにつき close します。
