### ISSUE TITLE
子テーマーが使えません

### ISSUE THREAD

**Issue by byron222** [vektor-inc/bill-vektor#170]
本ページの子テーマーをダウンロードして、インストールすると、「親テーマーbill-vektorがありません」と言われます。
ホームページからダウンロードする親テーマーとこちらのgithubからダウンロードする親テーマーはそもそも同じではないようです。
バージョンが違います。
テーマーの名前がメジャーアップデートなどで変わりました？

**Comment by kurudrive** [comment]
親のテンプレートでどれを参照するかか子テーマのstyle.cssに記載してあります。
参照しているのはディレクトリ名です。

https://training.vektor-inc.co.jp/courses/lightning-customize/lessons/how-to-use-child-theme-sample/

実際にサーバーに上がっているディレクトリ名にバージョン名がついているだけだと思います。
