### ISSUE TITLE
【確認待ち】インボイス制度対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/bill-vektor#175]
仕様
https://kigyou-kyoukasyo.com/tax/invoice-kakikata/

https://github.com/vektor-inc/bill-vektor/issues/174

**Comment by drill-lancer** [comment]
@kurudrive
仕様的にはこんな感じでいかがでしょうか？
![bill-vektor-bill](https://user-images.githubusercontent.com/38716787/196616301-244389ef-af03-4b7f-a82a-b97c0a22c150.jpg)
![bill-vektor-field](https://user-images.githubusercontent.com/38716787/196616308-f63e82ce-a8f0-44f2-9b04-34b3ccd28ab0.jpg)

下記と比較して検討をお願いします。
https://kigyou-kyoukasyo.com/tax/invoice-kakikata/

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます！良いと思います！！

**Comment by cloudservice0825** [comment]
インボイス制度の対応状況を教えてください。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
@cloudservice0825 基本的にはできています。
確認待ちですが、このプロジェクト自体採算があっていないため確認が後回しになっている状態です。

以下が開発中の対応バージョンとなりますので、不具合などあれば報告いただけると助かります。
※ ご利用の前にかならずバックアップをとってからインストールしてください。

[bill-vektor.zip](https://github.com/vektor-inc/bill-vektor/files/11974885/bill-vektor.zip)

**Comment by cloudservice0825** [comment]
ありがとうございます。
**bill-vektor.zip　をアップロードして、バージョンアップして、
インボイス制度の消費税の表示などの対応の確認をすることができました。

下記の内容の不具合があるようなので、手数をお掛けしますが、ご確認ください。
・見積書、請求書、領収書の品目の入力の幅が小さく、数量の入力の幅が大きいです。　参考　https://gyazo.com/cff3178bc7fbb95be7775eafe35067d8

**Comment by kurudrive** [comment]
@cloudservice0825 確認ありがとうございます！確かにそうですね。

@drill-lancer よろしくお願いいたします (￣人￣)

**Comment by drill-lancer** [comment]
@cloudservice0825
お使いのディスプレイの解像度を教えてください。

@kurudrive 
横幅が狭くなるとを下回ると品目の横幅が優先的に削られていくみたいです。

**Comment by cloudservice0825** [comment]
解像度は2560×1080です。ブラウザを大きくしたら大丈夫でしたが、
数量、単価、税抜/税込、消費税率の項目の幅が2/3位の固定にしていただけたら、ありがたいです。
ご検討をお願いいたします。

**Comment by drill-lancer** [comment]
@cloudservice0825 @kurudrive
とりあえず、横幅 1280px の画面サイズで問題ない表示になるように調整してみました。

**Comment by SanoHirotaka** [comment]
いつも利用させてもらっています。ありがとうございます。

適格請求書のルールで税率毎の計算は１回らしいのですが、各行で計算してから
合計されています。そのため端数処理でズレが発生しています。参考画像
![参考](https://github.com/vektor-inc/bill-vektor/assets/140033948/e234c81d-758b-4a20-9637-40ca4f05e325)

各行の消費税額、税込金額欄はハイフン表示で良いかもしれません。
下記は国税庁ＨＰにあった適格請求書の記載例です
![国税庁「適格請求書等保存方式の概要](https://github.com/vektor-inc/bill-vektor/assets/140033948/981ad38a-24be-4e9b-9bc6-202f22908d0d)

**Comment by kurudrive** [comment]
@SanoHirotaka 報告ありがとうございます！
@drill-lancer と、言う事でよろしくお願いいたします (￣人￣)

**Comment by drill-lancer** [comment]
@kurudrive 
> と、言う事でよろしくお願いいたします (￣人￣)

具体的には個別消費税額と税込金額の欄をハイフンにする or 必要ないから削除のどちらかであってますか？

**Comment by SanoHirotaka** [comment]
[drill-lancer](https://github.com/drill-lancer)
ご確認ありがとうございます。ハイフンにするで良いと思います。

**Comment by drill-lancer** [comment]
@kurudrive 
ハイフンにしておきました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。

@SanoHirotaka @cloudservice0825 

↓これでどうでしょう？

[bill-vektor.zip](https://github.com/vektor-inc/bill-vektor/files/12115366/bill-vektor.zip)

**Comment by SanoHirotaka** [comment]
はい、ありがとうございます！

**Comment by kurudrive** [comment]
リリーズ済みにつき close します。
みなさんありがとうございました。

**Comment by toshioq** [comment]
なるほどそんな罠があったのですね
理解しました。ありがとうございます。
