### ISSUE TITLE
領収書のメニューが表示されない。

### ISSUE THREAD

**Issue by Knobycyn** [vektor-inc/bill-vektor#177]
領収書プラグインを入れて、設定しましたが、トップページの左サイドバーに、見積書、請求書のメニューが出ているが、領収書のメニューが出てこないのですが、どうすれば良いでしょうか？

**Comment by Knobycyn** [comment]
早々に対応いただきありがとうございます。バッチうまくいきました。

**Comment by kurudrive** [comment]
@Knobycyn 無事表示できたようで何よりです。

**Comment by Knobycyn** [comment]
ただ、請求書から領収書を作成した際に、領収書のカテゴリーは、請求書のカテゴリーを踏襲しないのですね。
