### ISSUE TITLE
取引先での抽出

### ISSUE THREAD

**Issue by HS-masa** [vektor-inc/bill-vektor#188]
請求書や見積書などの管理画面で取引先での抽出をしたいケースが多々あります
請求書はタグで取引先を入力しているので管理画面の請求書リストでも取引先はわかるのですが
見積書はタグの設定もないしリストにタグも表示されないしで、確認のしようがありません

リストでの取引先の抽出ができればリスト上に取引先やタグの表示は必要ないので抽出機能があると嬉しいです

**Comment by kurudrive** [comment]
管理画面ではできないですが公開画面でできるのでこれではまずいですか？

![スクリーンショット 2023-08-17 20 28 09](https://github.com/vektor-inc/bill-vektor/assets/3272660/6369ac8d-914a-4d27-aa86-ca030986ec9d)

**Comment by HS-masa** [comment]
新たな請求を登録時に複写機能を使っているので管理画面でほしいのです

⁣BlueMail for Android から取得 ​

2023年8月17日 19:01、19:01、Hidekazu Ishikawa ***@***.***> のメッセージ:

**Comment by HS-masa** [comment]
そのツールでやってみます

⁣BlueMail for Android から取得 ​

2023年8月17日 20:08、20:08、Hidekazu Ishikawa ***@***.***> のメッセージ:
