### ISSUE TITLE
【領収書】プレビュー表示が一部のみ出力されます

### ISSUE THREAD

**Issue by yukino1230** [vektor-inc/bill-vektor#201]
領収書のプレビューで、こちらのように一部だけの表示になってしまいます。

BillVektor : 1.8.2
BillVektor Receipt : 1.2.1

試したこと
・BillVektor設定の再保存
・WP設定の各項目の再保存

何か改善方法があれば教えて下さると嬉しいです。

<img width="1355" alt="スクリーンショット 2023-08-03 0 19 56" src="https://github.com/vektor-inc/bill-vektor/assets/43793867/66c9577d-40c3-47e7-9472-1f142511a34d">

**Comment by kurudrive** [comment]
@yukino1230 報告ありがとうございます。ただいま修正しておりますので今しばらくお待ちくださいませ。

**Comment by kurudrive** [comment]
@yukino1230 ダウンロードページより bill-vektor-reciept の最新版（1.4.0）をダウンロードしてサイトにアップロードしてみてください。
https://vws.vektor-inc.co.jp/my-account/downloads

**Comment by drill-lancer** [comment]
@yukino1230
ダウンロードページから最新版がダウンロードできるようにしておきました。
一応キャッシュを削除してからお試しください。

**Comment by yukino1230** [comment]
@kurudrive 様

1.4.0をダウンロードできました。
プラグインを更新したところ、正常に表示されるようになりました。

迅速なご対応、大変感謝しております。
ありがとうございます！
