### ISSUE TITLE
【確認待ち】インボイス制度の登録番号のT + 13桁の番号　の「T」が表示されない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/bill-vektor#203]
https://vws.vektor-inc.co.jp/forums/topic/billvektor%e3%81%ae%e9%81%a9%e6%a0%bc%e8%ab%8b%e6%b1%82%e6%9b%b8%e7%99%ba%e8%a1%8c%e4%ba%8b%e6%a5%ad%e6%89%80%e7%99%bb%e9%8c%b2%e7%95%aa%e5%8f%b7%e3%81%ae%ef%bd%94%e6%96%87%e5%ad%97%e3%81%8c%e5%85%a5

対応案：
管理画面側のインボイス制度の登録番号の入力欄下に、以下もような注意文章が書いてあり、「T」の部分がフロント側にも表示されると良さそうです。

```
※「T」を除く半角数字13桁の半角数字をご入力ください。
```
---

Asigneesには、石川さんとリックさんを入れさせていただきました。

**Comment by drill-lancer** [comment]
@kurudrive 
番号だからといって数字のみとは限らないのですね。
https://github.com/vektor-inc/bill-vektor/blob/1dde913899c8a44f58d09ce3083df85143ba2851/inc/setting-page/setting-page.php#L42-L46

P.S,
石川さんのインボイス制度の登録番号も先頭「T」ですか？
