### ISSUE TITLE
Q: 消費税額と税込金額が表示されない

### ISSUE THREAD

**Issue by koike-moyashi** [vektor-inc/bill-vektor#209]
使用環境：php 8.1
BillVector：1.9.0
WordPress： 6.3
場所：見積もり、請求の表示画面

素晴らしいプロダクトの公開ありがとうございます。そろそろインボイス対応をと思い、インボイス対応前のバージョンから1.9.0に更新しました。1点質問があります。

1. 印刷側画面（編集ではなく表示）の各行の消費税額と税込金額が`-`なのは、インボイス対応ではこう言う見積、請求を表示する決まりなのでしょうか？template-parts/doc/table-price.phpのソースコードを見ても、上部では$item_tax_value_print、$item_total_printを計算していますが、表示部分では固定で-を入れているようです。

https://github.com/vektor-inc/bill-vektor/blob/105bc23152072110f030c7c9edb057b5d5cb4136/template-parts/doc/table-price.php#L95C1-L102C29

![2023-08-18_11h22_17](https://github.com/vektor-inc/bill-vektor/assets/4363429/74e9bc83-81a2-492c-9b4f-58e5964d86ef)

2. 私の環境では、template-parts/doc/table-price.phpの31行目を`foreach ( $bill_items as $bill_item )` → `foreach ( $bill_items as $key => $bill_item )`しないと、テーブルタグ側（96行目など）の`echo $key;`が定義されてないエラーになり、動作しませんでした（こちらは報告です）。

https://github.com/vektor-inc/bill-vektor/blob/105bc23152072110f030c7c9edb057b5d5cb4136/template-parts/doc/table-price.php#L31

**Comment by kurudrive** [comment]
@koike-moyashi おそらく - の表記で良いのだと思います。解釈が間違っていましたら別途ご指摘いただけると助かります。

https://github.com/vektor-inc/bill-vektor/issues/175#issuecomment-1643024858

**Comment by kurudrive** [comment]
@koike-moyashi 報告ありがとうございます。 2 の方は 1.9.1 で修正しました。

**Comment by koike-moyashi** [comment]
@kurudrive 
なるほど。1行づつ計算すると最後の金額がずれるのでこうなっているのですね。承知しました。ありがとうございます。
