### ISSUE TITLE
明細行の消費税額・税込金額が表示されません

### ISSUE THREAD

**Issue by toshioq** [vektor-inc/bill-vektor#212]
明細行に項目として消費税額・税込金額がありますが「-」表示のままで金額が表示されません

**Comment by toshioq** [comment]
table-price.php内に変数があったので、書き換えたら普通に表示できましたが
標準で明細行の消費税額と税込金額を表示していないのは何か意図があるのでしょうか

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/bill-vektor/issues/175#issuecomment-1643024858
