### ISSUE TITLE
消費税の非課税対応と、「消費税額」「税込金額」のところが「-」なることについて

### ISSUE THREAD

**Issue by nakashima01** [vektor-inc/bill-vektor#216]
お世話になります。
最新のバージョン: 1.10.0にアップデートしました。

請求書発行で、
顧客に、交通費の建て替えをしており「非課税の扱い」が必要です。

バージョンアップ前（インボイス対応前）までは、
税込みにして、行の中で、課税、非課税を混ぜて対応していました。

しかし、インボイス対応となると同対応ができません。

バージョン: 1.10.0にアップデートしてから、何をどうしても課税になってしまいます。
どのように対応したら良いのでしょうか？

それと、請求書の印刷画面で、行ごとの「消費税額」「税込金額」のところが「-」なるのでなぜでしょうか？
ご教授ください。

**Comment by kurudrive** [comment]
> それと、請求書の印刷画面で、行ごとの「消費税額」「税込金額」のところが「-」なるのでなぜでしょうか？
ご教授ください。

https://github.com/vektor-inc/bill-vektor/issues/212
https://github.com/vektor-inc/bill-vektor/issues/209

**Comment by kurudrive** [comment]
@drill-lancer 非課税の処理追加できます？課税のプルダウンに非課税含めるのが妥当かなとは思いますがどうでしょう？

**Comment by drill-lancer** [comment]
@kurudrive 
それなりに対応しておきました。
develop にコミットしてしまいましたが revert とかする気力はもうないのでこのままお願いします。
https://github.com/vektor-inc/bill-vektor/pull/218

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。領収書の方もよろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
領収書には対応が必要な部分は見当たりませんでした。
（こちらを読み込んで処理している部分のみ）

**Comment by kurudrive** [comment]
@drill-lancer あ、失礼しました。確認しました。対応ありがとうございます。

**Comment by kurudrive** [comment]
@nakashima01 1.11.0 にて対応しましたのでアップデートの上ご確認ください。

以上よろしくお願いいたします。

**Comment by nakashima01** [comment]
恐れります。先ほど確認できました。
早速のご対応感謝いたします。
