### ISSUE TITLE
BillVektor Receipt 領収証の発行ができなくなりました

### ISSUE THREAD

**Issue by kaiogojo** [vektor-inc/bill-vektor#217]
数日前に気付いたのですが、領収書発行ができず、以下のようなエラーが出ます。
BillVektorのアップデートが絡んでいるのでしょうか？
請求書・見積書発行は正常にできています。
対処法がありましたら、教えてください。

Wordpress、プラグイン、テーマとも最新版にアップデートしております。

よろしくお願いいたします。

＝＝ここから＝＝
Fatal error: Uncaught Error: Call to undefined function bill_total_add_tax() in /home/ogojo-nk/www/ogojo.com/kk/wp-content/plugins/bill-vektor-receipt/template-parts/doc/frame-receipt.php:51 Stack trace: #0 /home/ogojo-nk/www/ogojo.com/kk/wp-content/plugins/bill-vektor-receipt/bill-vektor-receipt.php(56): require_once() #1 /home/ogojo-nk/www/ogojo.com/kk/wp-includes/class-wp-hook.php(310): bvr_doc_frame_receipt('') #2 /home/ogojo-nk/www/ogojo.com/kk/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) #3 /home/ogojo-nk/www/ogojo.com/kk/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /home/ogojo-nk/www/ogojo.com/kk/wp-content/themes/bill-vektor/single.php(27): do_action('bill-vektor-doc...') #5 /home/ogojo-nk/www/ogojo.com/kk/wp-includes/template-loader.php(106): include('/home/ogojo-nk/...') #6 /home/ogojo-nk/www/ogojo.com/kk/wp-blog-header.php(19): require_once('/home/ogojo-nk/...') #7 /home/ogojo-nk/www/ogojo.com/kk/index.php(17): require('/home/ogojo-nk/...') #8 {main} thrown in /home/ogojo-nk/www/ogojo.com/kk/wp-content/plugins/bill-vektor-receipt/template-parts/doc/frame-receipt.php on line 51
＝＝ここまで＝＝

**Comment by kurudrive** [comment]
@kaiogojo 

ご連絡ありがとうございます。
念のため Billvektor と Receipt のバージョンを記載お願いできますでしょうか？
よろしくお願いいたします。

**Comment by kaiogojo** [comment]
ありがとうございます

BillVektorバージョン: 1.9.0
BillVektor Receipt　バージョン 1.3.0

よろしくお願いいたします

**Comment by kaiogojo** [comment]
Wordpress　バージョン 6.3.1
です

**Comment by kurudrive** [comment]
@kaiogojo とりあえず BillVektor 1.10.0 へのアップデート通知は出ていませんか？
出ていましたらアップデートを行ってください。

**Comment by kaiogojo** [comment]
BillVektor 1.10.0のアップデートの通知は今のところ出ていません
子テーマにしていたので、親テーマを有効にしてみたりしましたが、更新通知は出ていません。。

**Comment by kurudrive** [comment]
ダッシュボード > 更新 から 更新の再取得をしても通知は出ませんか？

**Comment by kaiogojo** [comment]
まだ出てこないです。。

**Comment by kaiogojo** [comment]
ちょっと待ってみます
また報告いたします

**Comment by kurudrive** [comment]
この 1.9.0 をアップしても更新通知は出ませんか？
https://github.com/vektor-inc/bill-vektor/releases/tag/1.9.0

**Comment by kaiogojo** [comment]
ちょっとやってみます

**Comment by kaiogojo** [comment]
1.9.0をアップしてみましたが、更新通知は出てきません

**Comment by kurudrive** [comment]
該当サイトはSSLは有効ですか？
PHPのバージョンはいくつですか？

**Comment by kaiogojo** [comment]
SSLは有効ですが
PHPが7.4.33 (モジュールモード)でした
PHPのバージョンが原因でしょうか？

**Comment by kurudrive** [comment]
アップデート通知が表示されない問題については環境依存の可能性があるため、
1.10.0を直接アップロードしてみてください。
https://github.com/vektor-inc/bill-vektor/releases/tag/1.10.0

**Comment by kaiogojo** [comment]
PHPを8.1（CGI)にアップしたら、更新通知が出たので、更新しました
エラー表示はなくなったのですが、宛先と「合計金額」という文字だけ表示されて、中身が反映されていませんでした

そこで、送っていただいたリンクから1.10.0を直接アップフォードしましたが、現象は同じでした

![スクリーンショット 2023-09-04 152731](https://github.com/vektor-inc/bill-vektor/assets/143978311/a7c9c911-d0ff-44fa-9597-30fbad74fadb)

**Comment by kurudrive** [comment]
BillVektor Reciept は現状 1.4.0 が最新版です。
管理画面にアップデート通知が出ない場合は
マイページ > ダウンロード からダウンロード＆アップロードして確認ください。
https://vws.vektor-inc.co.jp/my-account/downloads

**Comment by kaiogojo** [comment]
BillVektor Recieptを教えていただいた通り、再ダウンロード＆アップロードで、直りました！
BillVektor Recieptの方も更新通知が表示されてなく、サイトでも最新Ver.が確認できなかったので、1.3.0が最新だと思い込んでました
領収書発行はたまにしか使わないのですが、重宝していたので、大変助かりました
解決まで丁寧に説明とサポートいただき、ありがとうございました
