### ISSUE TITLE
【確認待ち】請求品目、見積品目の項目移動について

### ISSUE THREAD

**Issue by snoow3** [vektor-inc/bill-vektor#219]
請求書、見積書、いずれもドラッグで品目の順番入替が出来ると思います。
インボイス制度の対応Verにしてからだと思いますが、順番入替がうまく反映されないことがあるのと、
税率がドラッグについてこず、別の項目で税率計算されたりします。
これは環境による不具合なのでしょうか？

WordPress: 6.3.1
BillVektor: 1.11.0（自動更新）
Google Chrome 最新版

**Comment by kurudrive** [comment]
@drill-lancer 確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
私の環境では普通に並び替えできました。
コンソールエラーも表示されません。

**Comment by snoow3** [comment]
ご確認いただきましてありがとうございます。
改めて確認しましたのでスクショ貼ります。
Aの状態から3行目をドラッグで1行上にあげたのがBです。

子テーマで表示の修正を少ししていますので下記2ファイルは触っています。
/template-parts/doc/frame-estimate.php
/template-parts/doc/table-price.php
![kanriA](https://github.com/vektor-inc/bill-vektor/assets/144099181/39cbc359-d525-4f41-af61-11083ee7be0c)
![koukaiA](https://github.com/vektor-inc/bill-vektor/assets/144099181/c9c93ede-4036-4dca-95c4-8fa1cf7c544f)
![kanriB](https://github.com/vektor-inc/bill-vektor/assets/144099181/4ed4835b-e88b-486d-acbf-70cb0c4de1e8)
![koukaiB](https://github.com/vektor-inc/bill-vektor/assets/144099181/a44a7598-2e7f-44bf-8f66-c465fec7838b)

**Comment by drill-lancer** [comment]
@snoow3
親テーマに切り替えた場合はどうですか？

**Comment by snoow3** [comment]
親テーマに切り替えて同じ手順で操作してみましたが動作は変わらないです。
変更後の出力画面（親テーマ）スクショです。
![親テーマ公開B](https://github.com/vektor-inc/bill-vektor/assets/144099181/7331e044-769d-41b6-b9b2-399a52daab3a)

**Comment by drill-lancer** [comment]
@snoow3 
その症状が 100% 発生する手順は書けますか？

**Comment by snoow3** [comment]
不慣れですみません。修正始まっているのでしょうか？

@drill-lancer 
元々税率10％しか使っておらず、利用している現場からうまくドラッグで動かないという話が出たため、
「反映されないことがある」という表現をしていましたが、
非課税が導入されて確認したところ税率の反映も問題ある事に気が付き、
私の環境では税率のズレは毎回発生します。

**Comment by drill-lancer** [comment]
@snoow3 
上記コメントをしてから 100% 再現する手順を発見いたしまして
原因も特定しまして修正しました。
あとは @kurudrive 社長の確認＆リリース待ちといったところです。

**Comment by kurudrive** [comment]
ごはんたべてから今晩確認・リリースします。

**Comment by kurudrive** [comment]
@snoow3
本件 リリーズ済みですのでアップデートの上ご確認ください。
ご報告ありがとうございました。

**Comment by snoow3** [comment]
@kurudrive @drill-lancer 
アップデートして確認しました。問題なく動作しております！
ご対応ありがとうございました。
