### ISSUE TITLE
品目で項目を増やしたり削除したりできるようにしてほしい。

### ISSUE THREAD

**Issue by bybt-waki** [vektor-inc/bill-vektor#222]
はじめまして。
追加いただきたい機能があり書き込みさせていただきました。

請求品目、見積品目の項目を追加、削除したりできるようにしていただきたいです。
例えば、「産地」や「規格」など金額には影響ない項目を追加削除できるようにしたいのですが可能でしょうか？
出力される請求書や見積書、納品書には表示されなくても大丈夫です。
WP上で各品目の詳細を確認できるようにしたいです。

ご検討のほどよろしくお願い申し上げます。

<img width="1153" alt="20230914" src="https://github.com/vektor-inc/bill-vektor/assets/144987287/27fe98c3-5983-4b80-a075-2cb5723a0380">

**Comment by kurudrive** [comment]
@bybt-waki ご意見ありがとうございます。
ご連絡の件について、実装するとなると数十万程度〜100万円程度の開発コストがかかりますが、
大変申し上げにくいのですが、BillVektor 自体まったく収益になっておらず、
弊社の業績自体も好調とは言い難いため、採算の目処が立たない無償製品の機能追加に工数を割くのが難しい状況です。

ご期待に添える回答ができず恐れ入りますが、品目の列の中や、
品目の列を増やしてそこに入力しているなど、運用にてカバーいただくか、
ソースコード自体はこちらで公開してありますので、他の開発者への実装依頼などご検討くださいませ。

以上よろしくお願いいたします。
