### ISSUE TITLE
請求書の編集画面を開くと、税別に設定した見積品目が税抜に変わる

### ISSUE THREAD

**Issue by Crescendi-A** [vektor-inc/bill-vektor#223]
一度保存した請求書の編集画面を開くと、「税抜」に設定していた請求品目の「税抜/税込」欄が「税込」になる。
気づかずに保存すると請求金額が変わってしまうため、修正いただけると幸いです。

**Comment by drill-lancer** [comment]
@Crescendi-A 
いろいろ試してみましたが、最新版ではそのような事象は発生しませんでした。

そのような事象が過去にはありましたが最新版では修正済みです。
https://github.com/vektor-inc/bill-vektor/issues/219

最新版は 1.11.1 で下記から入手可能です。
https://github.com/vektor-inc/bill-vektor/releases/tag/1.11.1

**Comment by Crescendi-A** [comment]
最新版では問題ないことを確認いたしました。
たいへんお手数をおかけいたしました。
