### ISSUE TITLE
印鑑画像のサイズ調整について

### ISSUE THREAD

**Issue by cloudyman98** [vektor-inc/bill-vektor#229]
文字のサイズやテーブルレイアウト等は調整できたのですが、印鑑画像のサイズの調整がよく解らず。現時点でどのようにしたら良いか、ご教示願えないでしょうか。実際に合わせて、サイズを少し小さくしたいのです。

**Comment by kurudrive** [comment]
外観 > カスタマイズ > 追加CSSに

```
.bill-seal {
	width:50px;
}
```

とかでいけるかと思います。

**Comment by cloudyman98** [comment]
出来ました。ありがとうございました。
