### ISSUE TITLE
テーマのアップロードで互換性のないアーカイブが表示されました

### ISSUE THREAD

**Issue by ping-asucot** [vektor-inc/bill-vektor#232]
新規にｘサーバにインストールしたWordPeress 6.4.3 ですが
https://billvektor.com/howto/install/
【 ダッシュボード 】>【 外観 】>【 テーマ 】>【 新規追加 】>【 テーマのアップロード 】>【 ファイルを選択 】から先程ダウンロードした「bill-vektor.zip」を行ったのすが
下記のように　互換性のないアーカイブがでました。
![image_2024_03_08T07_59_06_564Z](https://github.com/vektor-inc/bill-vektor/assets/39787105/b108b679-547a-4b6a-9a28-be0547d60297)

WordPeress のバージョンをダウングレードした方がよいのでしょうか

**Comment by goutetsuguma** [comment]
@ping-asucot さま

[WordPress 6.4.3に関連する問題 ](https://core.trac.wordpress.org/ticket/60398)のようです。
お手数おかけしますが、お急ぎの場合は SFTP などで直接アップするか、6.4.2 に一旦ダウングレートしてみてください

**Comment by kurudrive** [comment]
@ping-asucot データを調整いたしましたので改めてダウンロードください。

**Comment by kurudrive** [comment]
返答ありませんが対応済みですので close します。
