### ISSUE TITLE
freee会計用のCSVについて

### ISSUE THREAD

**Issue by M-swd** [vektor-inc/bill-vektor#233]
Windowsユーザーです。MFクラウド会計用のCSVは問題ありませんが、freee会計用のCSVは文字化けしています。改善されませんでしょうか？

**Comment by kurudrive** [comment]
@M-swd 

正直なところ freee 自体で請求書も発行できるので実際 BillVektor 不要じゃないですか？
と、いう事もあり作業意欲が...。
freeeの請求書ではなく BillVektor を使用するメリットは何かありますか？

**Comment by kurudrive** [comment]
特に回答がありませんので本件一旦closeさせていただきます。
