### ISSUE TITLE
請求額が内税の場合、自動計算で税別になり使いづらいです

### ISSUE THREAD

**Issue by shujibaba** [vektor-inc/bill-vektor#247]
税額と金額を自動計算ではなく、個別に入力できるようにできないでしょうか？
よろしくお願いいたします。

**Comment by kurudrive** [comment]
ご意見ありがとうございます。
残念ながら現状開発余力がないので機能追加の予定はありません (￣人￣)

ご自身でプログラムを書ける場合は使いづらくないようにクローンしてご自由に改変ください。
改変プログラムをプルリクエストいただければ確認の上マージさせていただきます。

※ 開発予定がないのに返信しないでほっておくと「いつか追加されるかもしれない」と希望を持ってしまうのもよくないのであえて書かせていただきました。
