### ISSUE TITLE
各見積書・請求書事に消費税ありなしの設定

### ISSUE THREAD

**Issue by Bis-sup** [vektor-inc/bill-vektor#71]
税込み価格で金額を出さなければいけない時があるため、見積書や請求書作成時点で個別に消費税の計算を行うかどうかの設定ができるようになると非常にありがたいです。よろしくお願いいたします。

**Comment by kurudrive** [comment]
あぁ...そうですね...
最後に一括で税計算ではなく、各項目の時点で税込みで記入して、
現状の最後に一括で加算する項目をなくするという意味でしょうか？

**Comment by Bis-sup** [comment]
デフォルトでは税計算されてよいのですが、各項目ごとに「消費税計算をしない」というチェックボックスがあり、チェックが入っている項目は税計算を行わないというのがあると助かります。

それが難しいようでしたら、1つの見積書・請求書の合計額で消費税の計算をしないようにできるだけでも構いません。

Misoca(ミソカ)にこのような機能がついておりまして、例えば税込みで20,000円の請求書を出す際にはチェックを入れておくと消費税の計算が行われないため請求額を20,000円で出すことができます。
現状のBillVektorでは項目に20,000円を入力すると自動で消費税計算されてしまい請求額が21,600円となってしまいます。

わかりにくい説明で申し訳ありません。

**Comment by kurudrive** [comment]
@Bis-sup 
バージョン 0.5.3 で実装しましたので、最新版をお試しください。
