### ISSUE TITLE
見積品目・請求品目欄の各品目ごとに備考欄を

### ISSUE THREAD

**Issue by snowpoints** [vektor-inc/bill-vektor#93]
”bill-vektor"大変便利に活用しております。
今回は要望ですが、見積品目・請求品目欄の各品目ごとに備考欄を設置していただけると使い勝手がさらに向上するかと思います。
自身で挑戦いたしましたが、うまくいきません。
ご検討の程、よろしくお願いいたします。

**Comment by kurudrive** [comment]
こちらは 例えば普通に１行下に追加して、金額などは入力せずに 品目欄に備考を書けば運用でカバーできる（弊社ではそのようにして使っている）ため close とさせていただきます。
