### ISSUE TITLE
上部の合計金額と表の合計金額が違います。

### ISSUE THREAD

**Issue by vi-min** [vektor-inc/bill-vektor#96]
お世話になっております。
請求書の作成におきまして、上部の合計金額と表の合計金額が、1円、違ってしまいます。

小計の欄＋消費税の欄＝表の合計金額　　10,003円

小計の欄×1.08＝上部の合計金額（四捨五入 切り捨て）　10,002円

数字が統一されるようになるにはどうしたら良いでしょうか？

**Comment by kurudrive** [comment]
@vi-min 様

ご報告ありがとうございます。
すみません、ちょっと再現させて修正したいので、
表に入力している内容を書き込みいただけますでしょうか？
お手数おかけいたしますがよろしくお願いいたします。

**Comment by HayashiShigeru** [comment]
お世話になります。
同様の内容です。

1	式	¥ 5,000	¥ 5,000
1	式	¥ 10,000	¥ 10,000
1	式	¥ 17,500	¥ 17,500
1	式	¥ 25,000	¥ 25,000
1	式	¥ 0	¥ 0
1	式	¥ 10,000	¥ 10,000
1	式	¥ 40,000	¥ 40,000
1	式	¥ 5,000	¥ 5,000
1	式	¥ 5,000	¥ 5,000
1	式	¥ 15,000	¥ 15,000
1	式	¥ -39,963	¥ -39,963
1	式	¥ 3,760	¥ 3,760
で
小計	¥ 96,297
消費税	¥ 7,704
合計金額	¥ 104,001
なのですが、上部の合計金額は　￥ 104,000(消費税含)　となります。

	¥ -39,963を	¥ -39,964にしても同様に1円上部と下部が合わない金額で表示されます。

お手数ですが、よろしくお願いします。

**Comment by kurudrive** [comment]
@HayashiShigeru @vi-min 様

ありがとうございます。修正版アップしましたので、バージョン 0.7.2 にてご確認ください。
https://github.com/vektor-inc/bill-vektor/releases

**Comment by HayashiShigeru** [comment]
早速に申し訳ございません。
ご丁寧にありがとうございます。

**Comment by kurudrive** [comment]
修正済み
